[2024-05-07 11:27:54,446] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[2024-05-07 11:27:54,446] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-05-07 11:28:03,190] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:28:03] "GET / HTTP/1.1" 200 -
[2024-05-07 11:28:06,820] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:28:06] "GET /predictdata HTTP/1.1" 200 -
[2024-05-07 11:28:40,574] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Coding and Dev\SportsManagement\ParScorePipeline\app.py", line 42, in predict_datapoint
    if (Pitch == 'bat'):
NameError: name 'Pitch' is not defined
[2024-05-07 11:28:40,588] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:28:40] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-05-07 11:30:29,918] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:30:29] "GET / HTTP/1.1" 200 -
[2024-05-07 11:30:31,635] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:30:31] "GET /predictdata HTTP/1.1" 200 -
[2024-05-07 11:30:41,535] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Coding and Dev\SportsManagement\ParScorePipeline\app.py", line 42, in predict_datapoint
    Pitch=request.form.get('Pitch')
NameError: name 'Pitch' is not defined
[2024-05-07 11:30:41,560] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:30:41] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-05-07 11:30:58,741] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:30:58] "GET / HTTP/1.1" 200 -
[2024-05-07 11:31:00,510] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:31:00] "GET /predictdata HTTP/1.1" 200 -
[2024-05-07 11:31:07,875] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Coding and Dev\SportsManagement\ParScorePipeline\app.py", line 42, in predict_datapoint
    Pitch=request.form.get('Pitch')
NameError: name 'Pitch' is not defined
[2024-05-07 11:31:07,876] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:31:07] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-05-07 11:32:52,953] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:32:52] "GET / HTTP/1.1" 200 -
[2024-05-07 11:32:54,504] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:32:54] "GET /predictdata HTTP/1.1" 200 -
[2024-05-07 11:33:01,047] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Coding and Dev\SportsManagement\ParScorePipeline\app.py", line 42, in predict_datapoint
    Pitch=request.form.get('Pitch')
NameError: name 'Pitch' is not defined
[2024-05-07 11:33:01,051] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:33:01] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[2024-05-07 11:41:20,087] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:41:20] "GET / HTTP/1.1" 200 -
[2024-05-07 11:41:21,746] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:41:21] "GET /predictdata HTTP/1.1" 200 -
[2024-05-07 11:41:33,104] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Coding and Dev\SportsManagement\ParScorePipeline\app.py", line 42, in predict_datapoint
    result = round(results[0])
NameError: name 'Pitch' is not defined
[2024-05-07 11:41:33,133] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:41:33] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
