[2024-05-07 11:43:07,038] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.102:5000
[2024-05-07 11:43:07,038] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-05-07 11:43:11,802] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:43:11] "GET / HTTP/1.1" 200 -
[2024-05-07 11:43:13,347] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:43:13] "GET /predictdata HTTP/1.1" 200 -
[2024-05-07 11:43:21,472] 31 root - INFO - New Data Point inside app.py

[2024-05-07 11:43:21,472] 838 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\Coding and Dev\SportsManagement\ParScorePipeline\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\Coding and Dev\SportsManagement\ParScorePipeline\app.py", line 32, in predict_datapoint
    logging.info(new_data)
NameError: name 'new_data' is not defined
[2024-05-07 11:43:21,477] 97 werkzeug - INFO - 127.0.0.1 - - [07/May/2024 11:43:21] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
